-- MySQL Script generated by MySQL Workbench
-- qui 07 mai 2026 08:12:56
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema banco
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema banco
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `banco` ;
USE `banco` ;

-- -----------------------------------------------------
-- Table `banco`.`pessoa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `banco`.`pessoa` (
  `pessoa_id` INT NOT NULL AUTO_INCREMENT,
  `pessoa_nome` VARCHAR(255) NOT NULL,
  `pessoa_email` VARCHAR(255) NOT NULL,
  `pessoa_senha` VARCHAR(45) NOT NULL,
  `pessoa_tipo` VARCHAR(255) NOT NULL,
  `pessoa_data_nascimento` DATE NOT NULL,
  `pessoa_peso` FLOAT NOT NULL,
  `pessoa_altura` FLOAT NOT NULL,
  PRIMARY KEY (`pessoa_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `banco`.`cuidado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `banco`.`cuidado` (
  `cuidado_id` INT NOT NULL AUTO_INCREMENT,
  `cuidado_nome` VARCHAR(255) NOT NULL,
  `cuidado_data_nas` VARCHAR(255) NOT NULL,
  `cuidado_foto` VARCHAR(200) NOT NULL,
  `fk_pessoa_cuidador` INT NOT NULL,
  `fk_pessoa_paciente` INT NOT NULL,
  PRIMARY KEY (`cuidado_id`),
  INDEX `fk_pessoa_cuidador_idx` (`fk_pessoa_cuidador` ASC) VISIBLE,
  INDEX `fk_pessoa_paciente_idx` (`fk_pessoa_paciente` ASC) VISIBLE,
  CONSTRAINT `fk_pessoa_cuidador`
    FOREIGN KEY (`fk_pessoa_cuidador`)
    REFERENCES `banco`.`pessoa` (`pessoa_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pessoa_paciente`
    FOREIGN KEY (`fk_pessoa_paciente`)
    REFERENCES `banco`.`pessoa` (`pessoa_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `banco`.`medicamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `banco`.`medicamento` (
  `medicamento_id` INT NOT NULL AUTO_INCREMENT,
  `medicamento_nome` VARCHAR(255) NOT NULL,
  `medicamento_foto` VARCHAR(200) NOT NULL,
  `medicamento_laboratorio` VARCHAR(255) NOT NULL,
  `medicamento_categoria` VARCHAR(255) NOT NULL,
  `medicamento_obervacao` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`medicamento_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `banco`.`prescricao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `banco`.`prescricao` (
  `medicamento_medicamento_id` INT NOT NULL,
  `cuidado_cuidado_id` INT NOT NULL,
  `cuidado_fk_pessoa_pessoa_id` INT NOT NULL,
  `cuidado_fk_pessoa_cuidador` INT NOT NULL,
  `prescricao_frequencia` INT NOT NULL,
  `prescricao_dosagem` FLOAT NOT NULL,
  `prescricao_horario_primeira_dose` DATETIME NOT NULL,
  `prescricao_data_inicio` DATE NOT NULL,
  `prescricao_observacao` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`medicamento_medicamento_id`, `cuidado_cuidado_id`, `cuidado_fk_pessoa_pessoa_id`, `cuidado_fk_pessoa_cuidador`),
  INDEX `fk_medicamento_has_cuidado_cuidado1_idx` (`cuidado_cuidado_id` ASC, `cuidado_fk_pessoa_pessoa_id` ASC, `cuidado_fk_pessoa_cuidador` ASC) VISIBLE,
  INDEX `fk_medicamento_has_cuidado_medicamento1_idx` (`medicamento_medicamento_id` ASC) VISIBLE,
  CONSTRAINT `fk_medicamento_has_cuidado_medicamento1`
    FOREIGN KEY (`medicamento_medicamento_id`)
    REFERENCES `banco`.`medicamento` (`medicamento_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_medicamento_has_cuidado_cuidado1`
    FOREIGN KEY (`cuidado_cuidado_id`)
    REFERENCES `banco`.`cuidado` (`cuidado_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;